#lang sicp

;; The sine of an angle (specified in
;; radians) can be computed by making use of
;; the approximation sin ⁡ x ≈ x if x is
;; sufficiently small, and the trigonometric
;; identity
;; 一个角的正弦(弧度制)可以用 当 x 足够小时 sin x ~= x 来估计, 并且三角函数成立

;;                  x             x
;; sin ⁡ x = 3 sin --- − 4 sin^3 ---
;;                  3             3

;; to reduce the size of the argument of
;; sin. (For purposes of this exercise an
;; angle is considered “sufficiently small”
;; if its magnitude is not greater than 0.1
;; radians.) These ideas are incorporated in
;; the following procedures:
;; 来化简 sin 的参数的大小.
;; (为满足这个练习的"足够小",
;; 一个角在它的大小小于等于 0.1 弧度时成立.)
;; 这个想法由如下函数注册:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))


;; 1. How many times is the procedure *p* applied when *(sine 12.15)* is evaluated?
;; 2. What is the order of growth in space and number of steps (as a function of a ) used by the process generated by the sine procedure when *(sine a)* is evaluated?
;; 1. 当(sine 12.15)被求值时, 函数 p 被调用了多少次?
;; 2. 当(sine a) 被求值时, sine 函数产生的进程在空间和步骤上的增长顺序(作为 f(a))是什么?

;; Ans:

;; 1) 5
;; 2) 递归 O(n), 但是 angle 每次除3, 只有 log_3 n 层调用, O(log n)
;; 递归 O(n), 但是 log n 层调用, O(log n)
