#lang sicp

;; Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.
;; 如下两个函数定义了一个使用了函数 inc, 可以将它的参数加 1, 和函数 dec, 将它的参数减 1, 的用于加合两个正整数的方法

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(define (+-2 a b)
  (if (= a 0)
      b
      (+-2 (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by each procedure in evaluating *(+ 4 5)*. Are these processes iterative or recursive?
;; 使用代换模型, 展示这两个函数求值 (+ 4 5) 的进程. 这些进程迭代还是递归?


;; Ans

;; (+ 4 5)
;; (inc (+ 3 5))
;; (inc (+ (inc (+ 2 5))))
;; ...
;;
;; recursive
;;
;; (+-2 4 5)
;; (+-2 3 6)
;; (+-2 2 7)
;; ...
;;
;; iterative
